version: 3 
tasks:
  
  default: task -l

  download:
    desc: download original documentation and convert it
    dir: modules/development/pages
    vars:
      SOURCES: https://raw.githubusercontent.com/apache/openwhisk/master/docs/
    cmds:
    - git commit -m "snapshotting before updating documentation" -a
    - for: 
      - actions
      - webactions
      - packages
      - parameters
      - annotations
      - actions-new
      - actions-actionloop
      - actions-nodejs
      - actions-python
      - actions-go
      - actions-java
      - actions-php
      - cli
      - feeds
      - reference
      - rest_api
      cmd:  |
            curl  -sL {{.SOURCES}}/{{.ITEM}}.md -o {{.ITEM}}.md
            pandoc -f markdown -w asciidoc {{.ITEM}}.md -o {{.ITEM}}.adoc

  fixes:
    desc: download original documentation and convert it
    dir: modules/development/pages
    cmds: 
    - sed -i.bak -e 's/wsk/nuv/g' -e 's/OpenWhisk/OpenWhisk and Nuvolaris/g' *.adoc